# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::205825744082:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::205825744082:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters

  mapUsers: |
    - userarn: arn:aws:iam::205825744082:user/admin
      username: admin
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-11T11:16:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1631"
  uid: 86402a4e-a9ff-4721-8c24-f0c4258f7440
